# must be unique in a given SonarQube Server instance
sonar.projectKey=ShoppingCart_Db

# --- optional properties ---

# defaults to project key
sonar.projectName=ShoppingCartGUI_project

# defaults to 'not provided'
sonar.projectVersion=1.0

# Analyze only main sources and tests explicitly
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# JaCoCo XML report path (Sonar needs the XML report path to compute coverage)
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.host.url=http://localhost:9000

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

# run with:

mvn clean verify sonar:sonar "-Dsonar.projectKey=ShoppingCart_Db" "-Dsonar.token=$SONAR_TOKEN" "-Dsonar.host.url=http://localhost:9000"